### ISSUE TITLE
Implement backend processes to provide geography support

### ISSUE THREAD

**Issue by kristenkam** [osmlab/maproulette#161]
Implement backend process that performs spatial join query between input maproulette challenge geometries and us census tiger state, metro, and county (if necessary) geometries. set geography of maproulette task/error to result of spatial join. Execute this process before task goes live.

Implement API Get call to indicate geography, api backend process to perform regular database query based on geography values (i.e, geography=California), returned task has geography value of "California".

**Comment by mvexel** [comment]
closing this for now, as the server components are likely to change significantly enough for this to be irrelevant.
