### ISSUE TITLE
Admin tasks list should allow filtering

### ISSUE THREAD

**Issue by grischard** [osmlab/maproulette#270]
http://dev.maproulette.org/admin/taskview/ shows 180407 tasks in random order. It would be more useful if that interface let the admins filter by challenge, status, etc.

**Comment by grischard** [comment]
Is this wontfix, without even a comment?

**Comment by mvexel** [comment]
Hi @grischard  -- there is no development on this version of MapRoulette, if you want to report something on the current MapRoulette, please head over to https://github.com/maproulette/maproulette2/issues

Thanks!
