### ISSUE TITLE
Add Bing imagery as background layer

### ISSUE THREAD

**Issue by abfab** [osmlab/maproulette#271]
Addition of imagery layer allows to perform some tests without the need to open any editor.

**Comment by mvexel** [comment]
I am in discussions with MS / Bing to allow using their imagery directly in MapRoulette.

**Comment by sfkeller** [comment]
Could you resolve the license question with MS / Bing?
Note that there is also MapBox Satellite imagery where I strongly assume that the license allows this.

**Comment by martijnv-telenav** [comment]
Not conclusively.

**Comment by sfkeller** [comment]
Regarding MapBox Satellite: I think this is legally possible (if you inform MapBox) and technically easy.
Do you accept pull requests?

**Comment by martijnv-telenav** [comment]
Yes gladly, but I would want to discuss this because I want the challenge to be able to set the base map layer.

**Comment by sfkeller** [comment]
That sounds good! 
Where do you want to discuss this and what is the timeframe until you think it's available?
I'm asking because our project about crosswalk detection based on satellite imagery has to make a go/no-go decision on using MapRoulette.

**Comment by mvexel** [comment]
That all depends :) I won't have much time to work on it myself. We can do it in stages if you need access to aerial imagery from within MapRoulette quickly. For example stage 1 could be just have aerial imagery available globally in MapRoulette (but it would not be the default). Stage 2 would then be to make it challenge dependent. 

A PR for having a global aerial imagery layer would not be hard, technically. I would just require that the use of the layer comes with the appropriate license or explicit permission.

**Comment by sfkeller** [comment]
I think you can close this issue!?
