### ISSUE TITLE
Prevent bbox downloads for large ways

### ISSUE THREAD

**Issue by PedaB** [osmlab/maproulette#293]
As discussed via Mail/IRC there are tasks with very long ways. For the JOSM/iD remote this results in a huge set of data (the bounding box of that way) to be downloaded where you actually only want to download the way.

It would be great if either the challenge provider could somehow prevent the bbox download or that users might select if they want bbox download or not. E.g. the challenge provider might add another property to GeoJSON like bbox: "yes|no". (I'm aware that this would be only possible for JOSM remote, not for iD).

**Comment by brycenesbitt** [comment]
Proposal: a challenge level setting 

"download" : "object".
or
"download" : "bbox".


Where object would just download the given OSM way/node/relation.  For some challenges that's all you need.
