### ISSUE TITLE
Baselayer and Overlay selection enhancement

### ISSUE THREAD

**Issue by PedaB** [osmlab/maproulette#311]
It would be nice if the baselayer on the MapRoulette website could be changed (possibly also overlays would be nice). For the way waterways direction challenge it would be great to have a map with contour lines. Therefore hikebikemap.org or the "Cycle Map"-style from the openstreetmap.org main site would be great. Or simply a hillshading overlay.

Either adding additional layers (or overlays) to leaflet, so the user can change the layers as needed or a way to configure the layers for challenge providers would be nice.

**Comment by mvexel** [comment]
See also #271
