### ISSUE TITLE
Support adding custom imagery

### ISSUE THREAD

**Issue by grischard** [osmlab/maproulette#317]
There is currently no way to add a custom imagery URL to maproulette that would be passed on to iD or JOSM. The two editors support it:

http://josm.openstreetmap.de/wiki/Help/Preferences/RemoteControl#imagery for JOSM with the remote API

https://github.com/openstreetmap/iD/blob/master/API.md#url-parameters for iD url parameters — the comment parameter might be useful too

**Comment by mvexel** [comment]
At least we have a satellite / aerial layer now... No other progress on this.

**Comment by grischard** [comment]
Is this wontfix?

**Comment by mvexel** [comment]
There is no active development on MapRoulette, please report to https://github.com/maproulette/maproulette2/issues
