### ISSUE TITLE
Proposed challenge: Fix chain stores

### ISSUE THREAD

**Issue by andrewpmk** [osmlab/maproulette#326]
See https://wiki.openstreetmap.org/wiki/Chain_Store_Cleanup

There are a lot of chain stores in OSM that are entered correctly. For example, in North America, there are thousands of McDonald's tagged "McDonalds" (should be McDonald's) and hundreds of Tim Hortons tagged "Tim Horton's" (should be Tim Hortons). Also there are stores in the wrong category, e.g. Subway fast food restaurants tagged amenity=restaurant (should be amenity=fast_food). It would also be helpful to add missing websites, missing operators (e.g. Yum! Brands for KFC/Taco Bell/Pizza Hut) and drive_through=yes/no.

**Comment by mvexel** [comment]
Good one. Do you want to try and create this one yourself or would you need assistance?

**Comment by andrewpmk** [comment]
I have no idea how maproulette works, someone else would have to help me. The wiki page I mentioned has a lot of examples, I'm sure more could be added. It would be best to only include the stores that have typos or which are obviously in the wrong category (like McDonald's which is amenity=restaurant). I don't want to include store closings (like Target Canada) because these need to be verified on the ground to make sure that they are actually closed. I've been trying to fix these manually using overpass turbo but there are far more than 1 person can do alone.
