### ISSUE TITLE
"Select an area to work in" appears to fail. no challenges presented

### ISSUE THREAD

**Issue by rweait** [osmlab/maproulette#328]
I want to select the Speed Report challenge, and select an area near my home.  I can select the Speed Report challenge, and it presents challenges as expected.  

To select an area to work in I: 
click on an area on the map, a circle appears.
click in the notification box to confirm.

I expect to then be presented with a challenge in my selected area.  

Instead, I am given an empty list of available challenges in my area.  This should  (?) occur when the selection area is too small and no challenge tasks exist in the area.  I attempted to select areas large enough and diverse enough that the areas include challenges from Speed Reports, at least.

**Comment by mvexel** [comment]
Confirmed.

**Comment by rweait** [comment]
I've found one challenge that allows selecting an area, osmose-1120-highway-continuity.  I was able to select an area near Québec and get tasks.  Requesting the polygon fails, though.  

curl localhost:8000/api/challenge/osmose-1120-highway-continuity/polygon
{"status": 403, "message": "Forbidden"}

**Comment by rweait** [comment]
"maproulette/helpers.py" 307L 
in  refine_with_user_area(query):

Is POINT a problem for challenges that are composed of linestrings only, and no points?  

...            cast(from_shape(Point(session["lon"], session["lat"])), Geography),  ...
