### ISSUE TITLE
Mapillary integration

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette#329]
Would be neat to be able to show Mapillary images near MapRoulette tasks if available.

**Comment by erjiang** [comment]
Is there already a concept for how this would work/look? Would it maybe draw mapillary tracks in a different color than blue on the map when previewing the task?

**Comment by mvexel** [comment]
I haven't really thought about it very deeply yet. My initial thought would be to show Mapillary traces in a different color, but if their API supports it we can also query for the 10 or so closest images to the task (using a bounding box with a buffer or something like that.)
