### ISSUE TITLE
After username change on OSM MapRoulette still displays old one

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/maproulette#331]
It is possible to change username via settings ( https://www.openstreetmap.org/user/{username}/account ).

I change username months ago, MapRoulette continues to display "signed in as {old_username}. sign out" in menu.

Clearing cache and waiting months after username change failed to fix issue.

**Comment by mvexel** [comment]
yes, that data is retrieved from OSM once and then stored locally. Ideally this would be re-read from OSM from time to time.
