### ISSUE TITLE
Proposed challenge: ways exiting a roundabout where a way enters the roundabout

### ISSUE THREAD

**Issue by MaartenDeen** [osmlab/maproulette#332]
I got the idea from [bug #1395](https://github.com/Project-OSRM/osrm-backend/issues/1395) from the osrm buglist.

The [OSM wiki on roundabouts](http://wiki.openstreetmap.org/wiki/Tag:junction%3Droundabout) says: "Each road has to be connected with the roundabout in a separate node, i.e. between these nodes a segment of the roundabout is required. Thus routers can safely recognise that a section of the roundabout has to be driven through.".
IMHO this is a very reasonable demand. If you can bypass a roundabout without traversing it, you should map it without touching the roundabout. In other cases, I do not see the need to make an entrance to and exit from a roundabout from the same node.
This is also an easy fix: if you're unsure of the exact layout of the roundabout, add a very small section inbetween. Roads do not necessarily need to enter and exit a roundabout at fixed 45 degree angles (e.g. when from 4 directions dual carriageway roads enter).

It would improve the routing directions a great deal.

**Comment by mvexel** [comment]
Interesting idea. Who knows how to implement this as a challenge?

**Comment by kreed** [comment]
Osmose has a check for this called "roundabout shortcut"

http://wiki.openstreetmap.org/wiki/Osmose/issues#3010

**Comment by jwass** [comment]
Hi @MaartenDeen @mvexel - I was just revisiting that [OSRM roundabout issue](https://github.com/Project-OSRM/osrm-backend/issues/1395) I wrote earlier in the year and just found this discussion.

I was able to extract suspect roundabouts in the US - @Rub21 created a to-fix task that's available now on web and the to-fix JOSM plugin. http://osmlab.github.io/to-fix/#/task/roundaboutusa

**Comment by martijnv-telenav** [comment]
to-fix beat us to it!
