### ISSUE TITLE
Improved error messages from server : 409 : 500

### ISSUE THREAD

**Issue by brycenesbitt** [osmlab/maproulette#334]
Would be nice if:
{"status": 409, "message": "Conflict"}

Would read:
{"status": 409, "message": "Conflict starting at id=121232131313"}

And:
{"status": 500, "message": "Internal Server Error"}

Would read for JSON parse errors:
{"status": 500, "message": "Internal Server Error - JSON parsing"}

**Comment by mvexel** [comment]
Working on improved error messages. Should be on dev soon, on production at next release.
