### ISSUE TITLE
multilingual name tags in Ireland

### ISSUE THREAD

**Issue by bitnapper** [osmlab/maproulette#339]
Hi there, 
I think that maproulette could be a great help on improving data in Ireland. Ireland is mostly bilingual, Irish and English as you can see that on the bilingual streetsigns.

![Irish streetsigns](https://upload.wikimedia.org/wikipedia/commons/1/13/Durrow_roadsign.JPG)

That's why the Irish community maps names with three tags - especially streets and place names.

`name=Most comon name`
`name:ga=Irish name`
`name:en=English name`

Sad thing is, most places and streets are mapped with only a name tag containing sometimes an Irish and sometimes an English name. 

For rendering maps only containing Irish names this is a bit of a problem and having at least the name tagged as either language would make it easier for mappers to hund down the missing names. Also when the data is used in a context where the user can switch language this is a problem.

So it would be helpful to have a challenge where one could decide wether a street or a place having only a name tag has an English or Irish name and then adding the corresponding language tag.

Regards

bitnapper

**Comment by mvexel** [comment]
Hey @bitnapper  - thanks for the idea, seems like a good one. This sounds like something that could be detected with an Overpass query? In that case we could try the Magical MapRoulette Machine to get this up as a challenge?

**Comment by mvexel** [comment]
Does [this](https://github.com/mvexel/geojson2maproulette/blob/master/README.md) look like it would work?

**Comment by mvexel** [comment]
posted the challenge on dev.maproulette.org: http://dev.maproulette.org/#t=cork_multilingualnames/f09e1e9d-c1db-436c-93fc-a300000aff8d
