### ISSUE TITLE
Proposed challenge: untagged railway crossings

### ISSUE THREAD

**Issue by fred702** [osmlab/maproulette#340]
Recently in the US there has been a [rise in crashes](http://www.nytimes.com/2015/06/29/technology/agency-taps-mapping-technology-to-curb-rail-crossing-accidents.html?_r=1) associated with railroad crossings [(railway=level_crossing)](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dlevel_crossing). The federal government has approached mapping companies to add crossing locations to their mapping software. OSM already has many of these mapped, but adding more would help improve safety especially with software like OsmAnd which can warn drivers when they approach safety hazards like railway crossings.

Finding them is pretty easy as they overlap highways on the same layer.

**Comment by mvexel** [comment]
Do you have a source file for these crossings? Or are you suggesting we should just detect where a highway=railway intersects with a highway=[road types] that don't already have a crossing tag?

That should be doable with an Overpass query, in which case we could use the Magical MapRoulette Machine to get this challenge up!

**Comment by fred702** [comment]
mvexel, 
Thanks for the quick reply.

I haven't done more than a brief web search, but [this may be the data](https://safetydata.fra.dot.gov/OfficeofSafety/publicsite/downloaddbf.aspx) mentioned. Since it's USDOT it may be public domain, but i'll let someone more fluent in legalese check that out if it's the route you want to go down.

The overpass method also has the advantage of being applicable worldwide.

**Comment by mvexel** [comment]
I tried downloading the CSV files but cannot open them on my computer (Mac OS). Hunch is some sort of character encoding issue.

Do you want to take a stab at an overpass query for these?

**Comment by fred702** [comment]
I'm not sure how to do it in overpass, but keepright can [identify them](http://keepright.ipax.at/report_map.php?zoom=11&lat=44.19934&lon=-70.3653&layers=B0T&ch=0%2C150&show_ign=1&show_tmpign=1).

**Comment by fred702** [comment]
I see a lot of progress has been made on this challenge, thanks @mvexel ! One thing I noticed is that sometimes crossings may appear to be tagged correctly but are not actually on the intersecting node. I've even noticed two overlapping nodes which were both tagged with railway=level_crossing but were not connected. Without a manual inspection of the data, some of these errors may be missed.

**Comment by mvexel** [comment]
Yes it's looking good. hoping to publish soon!

**Comment by mvexel** [comment]
this is now live
