### ISSUE TITLE
Proposed challenge: Korean bridges as nodes

### ISSUE THREAD

**Issue by mxa** [osmlab/maproulette#344]
In South Korea there are a lot of features which have obviously been imported. Like bridges, which are mapped as points instead of as a segment of a way (road, train track, etc).Here is an example: http://www.openstreetmap.org/node/414964945#map=19/35.47293/128.25836  Additionally the naming convention has changed, so that instead of `bridge:name=봉수교 (Bongsugyo)` it should be `name=봉수교`, `name:kr=봉수교`, `name:en=Bongsu Bridge`, `name:ko_rm=Bongsugyo`
A few meters north-west of the example point are two more nodes along the highway that mark beginning and end of a bridge.

Here is more about mapping bridges in Korea: http://wiki.openstreetmap.org/wiki/Korea_bridges

**Comment by mvexel** [comment]
Would this pertain to all nodes that are tagged bridge=yes? Or is there a different / better way to query these nodes?

**Comment by mvexel** [comment]
If it is that simple, this should be the source dataset: http://overpass-turbo.eu/s/aZU

**Comment by mvexel** [comment]
(Assuming you mean South Korea when you speak about Korea.)

**Comment by mxa** [comment]
Yes,  AFAIK there was no such import in North Korea, but I didn't check. 

Am 18. August 2015 03:29:23 GMT+09:00, schrieb Martijn van Exel <notifications@github.com>:
>(Assuming you mean South Korea when you speak about Korea.)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/osmlab/maproulette/issues/344#issuecomment-131918214

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mvexel** [comment]
Saving the data in a [gist](https://gist.github.com/mvexel/bf808ed5a17098e29b98) for later.

**Comment by mxa** [comment]
This one is a hot candidate too. Please move :)

**Comment by mvexel** [comment]
This issue was moved to maproulette/challenge-ideas#2
