### ISSUE TITLE
Proposed challenge: Junctions in Korea

### ISSUE THREAD

**Issue by mxa** [osmlab/maproulette#345]
Junctions and their names are very important in Korea and Japan, because people will reference those (instead of the street names) to describe a route or location. A junction with a name will be rendered in Mapnik, but unfortunately many junctions are mapped (imported?) as single points close to the actual junction. Like this one: https://www.openstreetmap.org/node/414694520
Task would be to move those points into the actual junction and fix the naming scheme.

**Comment by mvexel** [comment]
How could you select these from the data? Is there a common tag?

**Comment by mxa** [comment]
I guess you could search for points (nodes not part of a way) that have the junction=yes key/value. 

Am 18. August 2015 03:17:40 GMT+09:00, schrieb Martijn van Exel <notifications@github.com>:
>How could you select these from the data? Is there a common tag?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/osmlab/maproulette/issues/345#issuecomment-131914599

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mvexel** [comment]
[This](http://overpass-turbo.eu/s/b09) query yields 3026 such junctions:

![screenshot 2015-08-17 16 02 41](https://cloud.githubusercontent.com/assets/120452/9317514/6a26d63c-44f9-11e5-8151-17956c736e60.png)

Saving the data in [a gist](https://gist.github.com/mvexel/454735d9ca96c0237222) for later.

**Comment by mxa** [comment]
hm.. why is the example point i linked to not showing up in the overpass-turbo query?

**Comment by mvexel** [comment]
your example does not have a `junction=yes` tag.

**Comment by mxa** [comment]
Right. I guess one could search for loose points containing the words *ogeori, *negeori, *sageori, *samgeori 

This is what they mean:


Quoting Wesley Woo-Duk Hwang-Chung:
> Ogeori = 5-way intersection
> Negeori = Sageori = 4-way intersection = crossroads
> Samgeori = 3-way intersection = T-junction

> I've often seen these labeled as "junction" on road signs, though, lost-in-translation notwithstanding. I suppose "n-way junction" might work.

**Comment by mxa** [comment]
Here is a page in the wiki which lists the intersections and how they should be translated to English.
https://wiki.openstreetmap.org/wiki/Korea_Naming_Convention#Common_Hangeul_expressions

**Comment by mxa** [comment]
Anything you need to make this happen?

**Comment by mvexel** [comment]
This issue was moved to maproulette/challenge-ideas#1
