### ISSUE TITLE
Contact the challenge admin

### ISSUE THREAD

**Issue by tuxayo** [osmlab/maproulette#346]
For example I would like to contact the admin of "Highway intersecting building" challenge to ask if it's still updated (because I enough tasks already fixed to start to doubt)

**Comment by mvexel** [comment]
Good point. Currently we don't keep track of who administers a challenge in the application. 

This is not something I can do easily without substantial changes to the application, but I will keep it open to consider it later.

By the way, I don't think this challenge is actively updated.

**Comment by tuxayo** [comment]
Thanks. So for now who should be contacted in order to contact a challenge admin?

**Comment by tuxayo** [comment]
?

**Comment by mvexel** [comment]
Best way is just to ask here and on maproulette@openstreetmap.org (subscription needed). We also have a slack channel, get an invite here: https://maproulette-slack-selfinvite.herokuapp.com/

**Comment by tuxayo** [comment]
Thanks!
