### ISSUE TITLE
Editing shortcut 'r' triggers a new task

### ISSUE THREAD

**Issue by ramyaragupathy** [osmlab/maproulette#347]
While trying to edit using shortcut `r`, the task area which is loaded in http://maproulette.org/, quickly switches to the next issue. 

The task now visible in the browser and that being worked on in JOSM is different and causes confusion over the current task. Using the `edit in JOSM` button instead of shortcut `r` works as expected.

![r](https://cloud.githubusercontent.com/assets/12103383/9083747/89c3a7c2-3b8a-11e5-96db-340a2fa45082.gif)

**Comment by mvexel** [comment]
The keyboard shortcuts have been broken for a little while. Apologies! If you can provide a fix, it would be appreciated!

**Comment by mvexel** [comment]
I think I have fixed this! Please re-open if you still see this issue.
