### ISSUE TITLE
 Maproulette loads the tasks into the same JOSM layer.

### ISSUE THREAD

**Issue by nikhilprabhakar** [osmlab/maproulette#349]
When loading a new task into JOSM from maproulette, the data is loaded onto the existing layer instead of a new one. This behaviour exists even after remote control has been configured to download objects into new layers.
![screen shot 2015-08-20 at 11 23 38 am](https://cloud.githubusercontent.com/assets/11845908/9376671/f55b3e1a-472d-11e5-88a0-d1cdfc95d6b8.png)

This can causes two potential issues:
- Large changesets if user does not upload data after each fix
- New users may end up uploading changes accidentally from previous issues that was meant to be skipped.
  Such an issue can be easily avoided by making sure every issue is loaded into a separate layer.

**Comment by mvexel** [comment]
This is intended behavior - initially we loaded each new task in a separate layer, which led to people complaining about JOSM having dozens of layers. So we changed it to load all tasks to the same layer. Maybe, in the future, we can make this a setting.

**Comment by planemad** [comment]
@mvexel is it possible to get the objects to a new layer if the JOSM remote control is configured that way? To avoid accidental edits I always use new layers and this is unsettling for me.
