### ISSUE TITLE
Proposed challenge: motorway_link without oneway tag

### ISSUE THREAD

**Issue by ghost** [osmlab/maproulette#350]
see [carto issue](https://github.com/gravitystorm/openstreetmap-carto/issues/1820)

Overpass turbo link:[motorway_link only](http://overpass-turbo.eu/s/blP)

There may be some highway=motorway that should have the oneway=no tag or be mapped as a dual carriageway but including that key in overpass yields too much noise.

**Comment by jojo4u** [comment]
This is very good suggestion. The german community already had two sprints doing this [1]. I drafted up a proposal to make oneway obligatory in our documentation[2]

[1] http://forum.openstreetmap.org/viewtopic.php?id=18932&p=1 
[2] http://wiki.openstreetmap.org/wiki/Proposed_features/Motorway_link_obligatory_oneway

**Comment by fred702** [comment]
Of course the German community is on top of it ;) @jojo4u I appreciate your efforts and documentation to improve this situation.
