### ISSUE TITLE
JOSM warning appears even though I don't use JOSM

### ISSUE THREAD

**Issue by neuhausr** [osmlab/maproulette#351]
I don't use JOSM, or even have it installed. But when I open a new task, I always get the red box with the warning "JOSM remote control did not respond. Do you have JOSM running with Remote Control enabled?" If MapRoulette is reading the preferences from our OSM account, shouldn't it be able to figure this out?

**Comment by mvexel** [comment]
This bug is actually unrelated to JOSM itself. It may have been fixed with a recent update, I haven't been able to reproduce. Let me know if it persists!

**Comment by neuhausr** [comment]
Also seems to be fixed, thanks again!
