### ISSUE TITLE
I click to edit in iD, iD opens, but no data is loaded

### ISSUE THREAD

**Issue by neuhausr** [osmlab/maproulette#352]
Here is an example URL that opens: https://openstreetmap.us/iD/release/#background=Bing&id=&map=18.00/-82.02230/34.49964 

This happens for me no matter the browser. I think it started happening a few weeks ago.

**Comment by harry-wood** [comment]
That URL is currently working for me, and opening with data, in both safari and chrome. I imagine this openstreetmap.us iD instance might've had a problem recently which has now been fixed

**Comment by mvexel** [comment]
I hope my latest updates fixed this, can you please verify?

**Comment by neuhausr** [comment]
Yes, working for me now, thanks!
