### ISSUE TITLE
Hide interface elements when no challenge is selected

### ISSUE THREAD

**Issue by harry-wood** [osmlab/maproulette#362]
When you're not signed in, seeing the welcome box, or when you are picking a challenge, it should hide some of the interface elements which are not applicable.  The "More help for this challenge" button, and everything below it. All of that is inactive unnecessary visual clutter until you're into a challenge. The box could grow taller, unhiding that stuff, when a challenge is selected.

Functionally it makes little difference, but I think it'll be a good "first impression" user experience improvement

**Comment by mvexel** [comment]
:+1:
