### ISSUE TITLE
'More help for this challenge' empty

### ISSUE THREAD

**Issue by harry-wood** [osmlab/maproulette#363]
I picked the top challenge in the list http://maproulette.org/#t=osmose-1070-1-overlap  and then tried to click "More help for this challenge"

There was no more help. Just a box repeating the challenge title.

I guess that's because some challenges don't have any more help written for them. So two possible solutions to this
- Always write some more help - Maybe that's a quick thing for someone to check. Go through the challenges. Check they all have some help text. Or maybe this could be a change to the challenge creation process. Could you de-list challenges until they provide help text?
- ....and/or a quick fix. Hide the 'More help for this challenge' button, if there's no more help.

**Comment by mvexel** [comment]
This is in the [challenge tutorial](https://gist.github.com/mvexel/b5ad1cb0c91ac245ea3f#help), but you're right this is not being enforced... I think it should be.

**Comment by harry-wood** [comment]
At the moment that says _"Having a Help text is optional but recommended."_  so that being the case, the thing to fix would be...

hide the 'More help for this challenge' button, if there's no more help.

**Comment by mvexel** [comment]
Let me see what I can do there!
