### ISSUE TITLE
Metrics: Display actual completion or actual remaining work

### ISSUE THREAD

**Issue by tuxayo** [osmlab/maproulette#376]
actual completion = (Fixed + False Positive + Already Fixed + Too hard to fix) /Number of Tasks

actual remaining work = (Available + Skipped) /Number of Tasks

Currently, when on a challenge metrics page, one have to calculate to get these values to know the challenge completion.

If a patch adding this would be accepted, I will try to implement this.

**Comment by tuxayo** [comment]
Oh sorry I opened the issue on the wrong repo, that's why it got closed right?

I transferred it on the correct repo: https://github.com/maproulette/maproulette2/issues/278

**Comment by mvexel** [comment]
Yes, thanks!
