### ISSUE TITLE
Convert NHD nodes into areas

### ISSUE THREAD

**Issue by andischan** [osmlab/maproulette#380]
From the [NHD](https://wiki.openstreetmap.org/wiki/National_Hydrography_Dataset) import we have ten thousands of nodes with waterway=dam or landuse=reservoir. These should be redrawn as areas.

According to Taginfo we still have [54.000 dam nodes](https://taginfo.openstreetmap.org/tags/?key=waterway&value=dam) and [62.000 reservoir nodes](https://taginfo.openstreetmap.org/tags/?key=landuse&value=reservoir). Despite this is big task I think we should start it.

Missing [US level crossing](https://github.com/mapbox/mapping/issues/111) was also quite big and Jochen Topfs _[old style multipolygons](http://area.jochentopf.com)_ challenge even started with 250.000 objects.

**Comment by mvexel** [comment]
Could you report this to https://github.com/maproulette/maproulette2/issues please?
